[package]
name = "complex_test"
version = "0.1.0"
authors = ["Marno Janetzky <janetzkymarno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
libc = "0.2.68"
